"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { AuthGuard } from "@/components/AuthGuard";
import { useAuth } from "@/contexts/AuthContext";
import { useCrypto } from "@/contexts/CryptoContext";
import { db } from "@/lib/firebase";
import { ref, set } from "firebase/database";
import { createKeyCheck, deriveKey } from "@/lib/crypto";

function firebaseErrorCode(error: unknown): string {
	if (typeof error === "object" && error !== null && "code" in error) {
		const code = (error as { code?: unknown }).code;
		return typeof code === "string" ? code.toUpperCase() : "";
	}
	return "";
}

function SetupInner(){const {user}=useAuth();const {unlock}=useCrypto();const router=useRouter();const [roomId,setRoomId]=useState("");const [otherUid,setOtherUid]=useState("");const [passphrase,setPassphrase]=useState("");const [confirmPassphrase,setConfirmPassphrase]=useState("");const [keyword,setKeyword]=useState("");const [confirmKeyword,setConfirmKeyword]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
async function submit(e:FormEvent){e.preventDefault();setError("");if(!user)return; if(!/^[A-Za-z0-9_-]{1,64}$/.test(roomId)){setError("Room ID may contain only letters, numbers, hyphens, and underscores.");return;} if(otherUid===user.uid){setError("The other participant must have a different UID.");return;} if(passphrase!==confirmPassphrase){setError("Passphrase confirmation does not match.");return;} if(keyword!==confirmKeyword){setError("Keyword confirmation does not match.");return;} setBusy(true);let stage="key derivation";try{const key=await deriveKey(passphrase,roomId);stage="verifier encryption";const keyCheck=await createKeyCheck(key);stage="Firebase room write";await set(ref(db,`rooms/${roomId}/meta`),{participants:{0:user.uid,1:otherUid},keyCheck});unlock(key,keyword);router.replace(`/chat/${encodeURIComponent(roomId)}`);}catch(error){const code=firebaseErrorCode(error);if(code.includes("PERMISSION_DENIED")||code.includes("PERMISSION-DENIED")){setError("Firebase denied the room write. Deploy the current rules and verify that you are signed in.");}else if(code.includes("NETWORK")||code.includes("DISCONNECTED")){setError("Firebase could not be reached. Check NEXT_PUBLIC_FIREBASE_DATABASE_URL.");}else if(code){setError(`Firebase error during ${stage}: ${code}.`);}else{setError(`Room creation failed during ${stage}. Confirm that this page is running on localhost or HTTPS, then retry.`);}}finally{setBusy(false);}}
return <main className="grid min-h-screen place-items-center p-6"><form onSubmit={submit} className="w-full max-w-md rounded-3xl border border-white/10 bg-white/[.04] p-8"><h1 className="text-2xl font-semibold">Room setup</h1><p className="mt-2 text-sm text-slate-400">The encryption passphrase and display keyword stay in memory and are never stored.</p><input required placeholder="Room ID" value={roomId} onChange={e=>setRoomId(e.target.value.trim())} className="mt-6 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3"/><input required placeholder="Other participant UID" value={otherUid} onChange={e=>setOtherUid(e.target.value.trim())} className="mt-3 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3"/><input required type="password" placeholder="Shared encryption passphrase" value={passphrase} onChange={e=>setPassphrase(e.target.value)} className="mt-3 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3"/><input required type="password" placeholder="Confirm encryption passphrase" value={confirmPassphrase} onChange={e=>setConfirmPassphrase(e.target.value)} className="mt-3 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3"/><input required placeholder="Shared display keyword" value={keyword} onChange={e=>setKeyword(e.target.value)} className="mt-3 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3"/><input required placeholder="Confirm display keyword" value={confirmKeyword} onChange={e=>setConfirmKeyword(e.target.value)} className="mt-3 w-full rounded-xl border border-white/10 bg-black/30 px-4 py-3"/>{error&&<p className="mt-3 text-sm text-red-300">{error}</p>}<button disabled={busy} className="mt-4 w-full rounded-xl bg-cyan-400 px-4 py-3 font-semibold text-slate-950 disabled:opacity-50">{busy?"Creating room…":"Create room"}</button></form></main>}
export default function SetupPage(){return <AuthGuard><SetupInner/></AuthGuard>}
